apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-service
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paymentService.service.type }}
  selector:
    app: payment-service
  ports:
    - port: {{ .Values.paymentService.service.port }}
      targetPort: {{ .Values.paymentService.service.port }}
      name: http
