apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
  labels:
    app: cart-service
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 8003
      targetPort: 8003
      name: http
