apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  init-databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE {{ .Values.userService.database }};
        CREATE DATABASE {{ .Values.productService.database }};
        CREATE DATABASE {{ .Values.cartService.database }};
        CREATE DATABASE {{ .Values.paymentService.database }};

        GRANT ALL PRIVILEGES ON DATABASE {{ .Values.userService.database }} TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE {{ .Values.productService.database }} TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE {{ .Values.cartService.database }} TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE {{ .Values.paymentService.database }} TO $POSTGRES_USER;
    EOSQL
