apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
  labels:
    app: product-service
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.productService.service.type }}
  selector:
    app: product-service
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: {{ .Values.productService.service.port }}
      name: http
