apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    {{- include "infra.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    {{- include "infra.labels" . | nindent 4 }}
data:
  init-databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    {{- range .Values.postgres.databases }}
        CREATE DATABASE {{ . }};
    {{- end }}

    {{- range .Values.postgres.databases }}
        GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO $POSTGRES_USER;
    {{- end }}
    EOSQL
